config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :lists do
    resources :bookmarks, only: [:index, :new, :create]
  end

  root 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, :list, presence: true
  validates :movie_id, uniqueness: { scope: :list_id, message: 'has already been bookmarked in this list' }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, uniqueness: true
  validates :name, :photo, presence: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true
  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create, :show]
  before_action :set_id_bookmark, only: [:destroy]
  # def index
  #   @bookmarks = Bookmark.where(list_id: params[:list_id])
  # end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def show
    @bookmarks = @list.bookmarks
  end

  def destroy
    @bookmark.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end

  def set_id_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @query = params[:query]
      @lists = list.where("name LIKE ?", "%#{params[:query]}%")
      # Preventing SQL Injection and Database error for
      # unknown characters
    else
      @lists = List.all
    end
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%# <div class="container mt-4">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%# <%= f.input :comment %>
    <%#= f.association :movie %>
    <%#= f.button :submit, class: "btn btn-primary" %>
  <%# end %>
<%# </div> %>

<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.input :comment %>
        <%= f.association :movie %>
        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="container">
  <%= simple_form_for(list) do |f| %>
    <%= f.input :name %>
    <%#= f.input :img_url %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/lists/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div >
      <h1>Edit List</h1>
      <div >
        <%= render "form", list: @list %>
      </div>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="banner">
  <div>
    <h1>Save any kind of movies</h1>
    <h2>Classic</h2>
  </div>
</div>
  <div class="button-addmovie-showpage">
    <div class="button-width">
      <%= link_to "Add List", new_list_path %>
    </div>
  </div>
<div class="container mt-5" >
  <% if @lists.empty? %>
    <h1>your data base is empty</h1>
  <% else %>
    <div class="movie-list-row">
      <% @lists.each do |list| %>
        <div class="movie-list-card" style="background-image: url('<%= cl_image_path list.photo.key, height: 300, width: 400, crop: :fill %>')">
          <div class="h2-center">
            <h2><%= link_to list.name, list_path(list) %></h2>
          </div>
          <div class="card-actions">
            <%= link_to edit_list_path(list), class: 'edit-link' do %>
              <%= content_tag :i, '', class: 'fa-solid fa-pen-to-square' %>
            <% end %>
            <%= link_to list_path(list),
                  method: :delete,
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                  class: 'delete-link' do %>
              <%= content_tag :i, '', class: 'fa-solid fa-trash' %>
            <% end %>
            <%= link_to "Add Bookmark", new_list_bookmark_path(list), class: "add_bookmark" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <h1>Add a new List</h1>
      <div>
        <%= render "form", list: @list %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<%# <img src="https://media.istockphoto.com/id/1372681569/nl/foto/hands-holding-a-film-slate-directing-a-movie-scene.jpg?s=612x612&w=0&k=20&c=GHBwhPaZ10BI4mKjhQGjt4Krngw1BzeyCVV9sP6ktCE=" alt="Banner Background"> %>
  <div class="banner-movie"style="background-image: url('<%= cl_image_path @list.photo.key, height: 300, width: 400, crop: :fill %>')">
      <div>
      <h1><%= @list.name %></h1>
    </div>
  </div>


<div class="row row-cols-1 row-cols-md-3 g-4">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="col">
      <div class="card">
        <img src="<%= bookmark.movie.poster_url %>" class="card-img-top" alt="Poster">
        <div class="card-body">
          <h5 class="card-title"><%= bookmark.movie.title %></h5>
          <p class="card-text"><%= bookmark.comment %></p>
        </div>
        <div class="card-footer">
          <%= link_to list_path(@list),
                    method: :delete,
                    data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                    class: 'btn btn-danger delete-link' do %>
            <%= content_tag :i, '', class: 'fa-solid fa-trash' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div>
    <img src="https://media.istockphoto.com/id/1164705522/nl/foto/popcorn-vliegt-uit-een-volle-emmer-close-up-op-een-witte-ge%C3%AFsoleerd.jpg?s=612x612&w=0&k=20&c=J4OYtuTRRA8YljGsQUFOf1lcWxoP7dNxIH_QEoEMy6g=" alt="poporn">
  </div>
  <div>
    <%= link_to "My Lists", root_path%>
    <%= link_to "New List", new_list_path %>
  </div>
</nav>